Repository dbt-labs/dbt-adapters, pull requests merged in 2024-02, with the labels that each got.

#62 Point check back to dbt-core version instead of the adapter version
  dbt/tests/adapter/basic/test_docs_generate.py
Labels: bug

#66 Add an implementation issue template for maintainers
  .github/ISSUE_TEMPLATE/internal-epic.yml
  .github/ISSUE_TEMPLATE/internal-feature-implementation.yml
Labels: support

#75 Update internal issue templates
  .github/ISSUE_TEMPLATE/internal-epic.yml
  .github/ISSUE_TEMPLATE/internal-feature-implementation.yml
Labels: support

#70 Add triaging action
  .github/workflows/resubmit-for-triage.yml
Labels: support

#79 Point CI testing to dev versions of internal dependencies
  dbt-tests-adapter/pyproject.toml
  pyproject.toml
Labels: cla:yes, Skip Changelog

#89 bump to 0.1.0a7
  dbt/adapters/__about__.py
Labels: Skip Changelog

#94 Readd removed logic for deferral fail-over
  dbt/include/global_project/macros/unit_test_sql/get_fixture_sql.sql
Labels: Skip Changelog

#97 Fix unit test behavior related to deferral.
  dbt/include/global_project/macros/unit_test_sql/get_fixture_sql.sql
Labels: Skip Changelog

#102 Fix testing migration
  dbt/tests/adapter/column_types/test_column_types.py
  dbt/tests/adapter/hooks/data/seed_model.sql
  dbt/tests/adapter/hooks/data/seed_run.sql
  dbt/tests/adapter/hooks/fixtures.py
  dbt/tests/adapter/hooks/test_model_hooks.py
  dbt/tests/adapter/hooks/test_run_hooks.py
Labels: pre-regression, Skip Changelog

#111 update dbt-common dependency to <2.0
  pyproject.toml
Labels: Skip Changelog

#104 Add version bump and changelog
  .github/actions/build-hatch/action.yml
  .github/actions/publish-pypi/action.yml
  .github/workflows/github-release.yml
  .github/workflows/release.yml
  .github/workflows/release_prep_hatch.yml
  .pre-commit-config.yaml
Labels: Skip Changelog

#116 Add docs section to epic and feature templates
  .github/ISSUE_TEMPLATE/internal-epic.yml
  .github/ISSUE_TEMPLATE/internal-feature-implementation.yml
  .github/pull_request_template.md
Labels: support
