Repository dbt-labs/dbt-adapters, pull requests merged in 2024-08, with the labels that each got.

#278 Update `setup-python` action to `v5` to move off of a deprecated version of Node (`node16`)
  .github/actions/setup-hatch/action.yml
Labels: cla:yes, Skip Changelog

#279 Update `download-artifact` to `v4`
  .github/actions/publish-pypi/action.yml
Labels: Skip Changelog

#280 Updating changie.yaml to add contributors and PR links
  .changes/unreleased/Under the Hood-20240801-220551.yaml
  .changie.yaml
Labels: cla:yes

#236 Use model alias for the CTE identifier generated during ephemeral materialization
  .changes/unreleased/Fixes-20240610-195300.yaml
  dbt/adapters/base/relation.py
  tests/unit/test_relation.py
Labels: cla:yes

#254 Update type hints for `get_adapter_constraint_support`
  dbt/adapters/factory.py
Labels: cla:yes, Skip Changelog
