Repository dbt-labs/dbt-adapters, pull requests merged in 2024-05, with the labels that each got.

#191 Cross-database `date` macro
  .changes/unreleased/Features-20240501-091604.yaml
  dbt-tests-adapter/dbt/tests/adapter/utils/fixture_date.py
  dbt-tests-adapter/dbt/tests/adapter/utils/test_date.py
  dbt/include/global_project/macros/utils/date.sql
Labels: cla:yes, user docs

#193 remove upper bound on dbt-core for dbt-tests-adapters
  dbt-tests-adapter/pyproject.toml
Labels: cla:yes, Skip Changelog

#194 remove reference to node.deffered in seed assertion for clone test
  .changes/unreleased/Fixes-20240502-150038.yaml
  dbt-tests-adapter/dbt/tests/adapter/dbt_clone/test_dbt_clone.py
Labels: cla:yes

#197 Adjust __post_serialize__ signature
  .changes/unreleased/Features-20240506-170313.yaml
  dbt/adapters/contracts/connection.py
Labels: cla:yes, Skip Changelog

#200 Create CODEOWNERS
  .github/CODEOWNERS
Labels: cla:yes

#201 Update CODEOWNERS to add dbt-labs/adapters
  .github/CODEOWNERS
Labels: cla:yes

#195 Add query recording for adapters which use SQLConnectionManager
  .changes/unreleased/Under the Hood-20240503-162655.yaml
  dbt/adapters/record.py
  dbt/adapters/sql/connections.py
  docs/README.md
  docs/guides/record_replay.md
Labels: cla:yes

#203 Improving message description for compile error in get_fixtu…
  .changes/unreleased/Features-20240511-032253.yaml
  dbt/include/global_project/macros/unit_test_sql/get_fixture_sql.sql
Labels: cla:yes, ok to test

#215 Add docstring for "catch all" relation type of `External`
  dbt/adapters/contracts/relation.py
Labels: cla:yes, Skip Changelog

#217 Improve memory efficiency of process_results by iterating.
  .changes/unreleased/Under the Hood-20240516-105757.yaml
  dbt/adapters/sql/connections.py
  tests/unit/test_sql_result.py
Labels: cla:yes
