Repository dbt-labs/dbt-adapters, pull requests merged in 2024-09, with the labels that each got.

#243 Snapshot time data type
  .changes/unreleased/Features-20240621-143024.yaml
  dbt/include/global_project/macros/adapters/timestamps.sql
  dbt/include/global_project/macros/materializations/snapshots/helpers.sql
  dbt/include/global_project/macros/materializations/snapshots/snapshot.sql
Labels: cla:yes

#292 Check if warning exists, for compatibility with 1.8
  dbt/include/global_project/macros/materializations/snapshots/helpers.sql
Labels: Skip Changelog

#282 Add Behavior Flag Framework
  .changes/unreleased/Features-20240818-005131.yaml
  .pre-commit-config.yaml
  dbt/adapters/base/impl.py
  tests/unit/conftest.py
  tests/unit/fixtures/__init__.py
  tests/unit/fixtures/adapter.py
  tests/unit/fixtures/connection_manager.py
  tests/unit/fixtures/credentials.py
  tests/unit/test_behavior_flags.py
Labels: cla:yes

#298 Revert "Bumping version to 1.4.2 and generate changelog"
  .changes/1.4.2.md
  .changes/unreleased/Features-20240621-143024.yaml
  .changes/unreleased/Features-20240818-005131.yaml
  CHANGELOG.md
  dbt/adapters/__about__.py
Labels: cla:yes

#285 Add EventTimeFilter and BaseRelation.render_event_time_filtered
  .changes/unreleased/Features-20240905-180956.yaml
  dbt/adapters/base/relation.py
  tests/unit/test_relation.py
Labels: cla:yes

#299 update dbt-common pin to >=1.8
  .changes/unreleased/Dependencies-20240909-200011.yaml
  pyproject.toml
Labels: cla:yes

#300 base microbatch support + tests
  .changes/unreleased/Features-20240911-135404.yaml
  dbt-tests-adapter/dbt/tests/adapter/incremental/test_incremental_microbatch.py
  dbt/adapters/__about__.py
  dbt/adapters/base/impl.py
  dbt/adapters/base/relation.py
  dbt/include/global_project/macros/materializations/models/incremental/strategies.sql
Labels: cla:yes

#305 add freezegun to dbt-tests-adapter dependencies
  dbt-tests-adapter/pyproject.toml
Labels: cla:yes, Skip Changelog

#306 Add behavior flags to jinja context
  dbt/adapters/base/impl.py
  dbt/adapters/base/meta.py
Labels: cla:yes, Skip Changelog

#308 Temporarily gate microbatch behind env var DBT_EXPERIMENTAL_MICROBATCH
  dbt/adapters/base/impl.py
Labels: cla:yes, Skip Changelog

#307 use patch_microbatch_end_time
  dbt-tests-adapter/dbt/tests/adapter/incremental/test_incremental_microbatch.py
Labels: cla:yes, Skip Changelog

#290 Snapshot column names
  .changes/unreleased/Features-20240903-155618.yaml
  dbt/adapters/base/impl.py
  dbt/adapters/exceptions/compilation.py
  dbt/include/global_project/macros/materializations/snapshots/helpers.sql
  dbt/include/global_project/macros/materializations/snapshots/snapshot.sql
  dbt/include/global_project/macros/materializations/snapshots/snapshot_merge.sql
  dbt/include/global_project/macros/materializations/snapshots/strategies.sql
Labels: cla:yes

#313 update Behavior Flag unit test fixtures
  tests/unit/test_behavior_flags.py
Labels: cla:yes, Skip Changelog

#296 Add pre-commit autoupdate workflow
  .github/workflows/precommit-autoupdate.yml
Labels: cla:yes, Skip Changelog

#314 Add required 'begin' config for testing microbatch models
  .changes/unreleased/Under the Hood-20240923-184719.yaml
  dbt-tests-adapter/dbt/tests/adapter/incremental/test_incremental_microbatch.py
Labels: cla:yes

#318 update dbt-common dependency to 1.10
  pyproject.toml
Labels: cla:yes, Skip Changelog
