Repository dbt-labs/dbt-adapters, pull requests merged in 2025-05, with the labels that each got.

#1016 Test packages against their deployment environment
  .github/workflows/_integration-tests.yml
  .github/workflows/_unit-tests.yml
  .github/workflows/_verify-build.yml
  .github/workflows/publish-internal.yml
  .github/workflows/publish-oss.yml
  .github/workflows/pull-request-checks.yml
  .github/workflows/scheduled-tests.yml
  dbt-adapters/hatch.toml
  dbt-athena-community/hatch.toml
  dbt-athena/hatch.toml
  dbt-bigquery/hatch.toml
  dbt-postgres/hatch.toml
  dbt-redshift/hatch.toml
  dbt-snowflake/hatch.toml
  dbt-spark/hatch.toml
Labels: cla:yes, skip:changelog-check

#1053 Align on `pytest` version of `7.x`
  dbt-adapters/hatch.toml
  dbt-athena-community/hatch.toml
  dbt-athena/hatch.toml
  dbt-snowflake/hatch.toml
  dbt-tests-adapter/hatch.toml
Labels: cla:yes, skip:changelog-check

#1055 correct cluster_by type check to return str as-is
  dbt-snowflake/.changes/unreleased/Fixes-20250501-160350.yaml
  dbt-snowflake/src/dbt/adapters/snowflake/parse_model.py
  dbt-snowflake/tests/unit/test_parse_model.py
Labels: cla:yes

#1054 Always run `dbt-spark` integration tests on `py3.10`
  .github/workflows/_integration-tests.yml
  dbt-spark/hatch.toml
Labels: cla:yes, skip:changelog-check

#1052 Keep `limit` as a required parameter in `get_test_sql`
  dbt-adapters/.changes/unreleased/Fixes-20250501-150241.yaml
  dbt-adapters/src/dbt/include/global_project/macros/materializations/tests/helpers.sql
  dbt-adapters/src/dbt/include/global_project/macros/materializations/tests/test.sql
Labels: cla:yes

#1062 dbt redshift/enable conn debug logger
  dbt-redshift/.changes/unreleased/Under the Hood-20250502-161914.yaml
  dbt-redshift/src/dbt/adapters/redshift/connections.py
Labels: cla:yes

#1057 Fix #1056: Keep table and column metadata as strings
  dbt-adapters/.changes/unreleased/Under the Hood-20250502-115115.yaml
  dbt-adapters/src/dbt/adapters/base/impl.py
Labels: cla:yes

#1069 fix and properly test new retry_all param
  dbt-redshift/.changes/unreleased/Fixes-20250506-134437.yaml
  dbt-redshift/src/dbt/adapters/redshift/connections.py
  dbt-redshift/tests/functional/adapter/test_exception_handling.py
Labels: cla:yes

#1071 [Bug] Apply cluster key to tables after table creation during a ctas statement
  dbt-snowflake/.changes/unreleased/Fixes-20250507-135848.yaml
  dbt-snowflake/src/dbt/include/snowflake/macros/relations/table/create.sql
Labels: cla:yes

#1064 overridable QueryComment append default by adapter, snowflake override
  dbt-adapters/.changes/unreleased/Features-20250506-110909.yaml
  dbt-adapters/src/dbt/adapters/base/query_headers.py
  dbt-adapters/src/dbt/adapters/contracts/connection.py
  dbt-snowflake/.changes/unreleased/Fixes-20250506-111546.yaml
  dbt-snowflake/src/dbt/adapters/snowflake/connections.py
  dbt-snowflake/src/dbt/adapters/snowflake/query_headers.py
  dbt-snowflake/tests/functional/adapter/query_comment_tests/test_query_comments.py
  dbt-snowflake/tests/unit/test_snowflake_adapter.py
Labels: cla:yes

#1074 add permissions for workflows
  .github/workflows/_publish-internal.yml
  .github/workflows/publish-internal.yml
  .github/workflows/publish-oss.yml
  .github/workflows/pull-request-checks.yml
  .github/workflows/scheduled-publishing.yml
  .github/workflows/scheduled-tests.yml
Labels: cla:yes

#1076 Revert "add permissions for workflows"
  .github/workflows/_publish-internal.yml
  .github/workflows/publish-internal.yml
  .github/workflows/publish-oss.yml
  .github/workflows/pull-request-checks.yml
  .github/workflows/scheduled-publishing.yml
  .github/workflows/scheduled-tests.yml
Labels: cla:yes

#1075 Add unit test for relation with oid exception handling and skip functional test
  dbt-redshift/tests/functional/adapter/test_exception_handling.py
  dbt-redshift/tests/unit/test_connection.py
Labels: cla:yes, skip:changelog-check, pkg:dbt-redshift

#1073 pin psycopg2-binary in hatch same as pyproject.toml
  dbt-postgres/hatch.toml
Labels: cla:yes

#1080 add permissions for workflows
  .github/workflows/_publish-internal.yml
  .github/workflows/publish-internal.yml
  .github/workflows/publish-oss.yml
  .github/workflows/pull-request-checks.yml
  .github/workflows/scheduled-publishing.yml
  .github/workflows/scheduled-tests.yml
Labels: cla:yes

#1082 add read all permission to PR CI
  .github/workflows/pull-request-checks.yml
Labels: cla:yes

#1081 add check for a label before running CI
  .github/workflows/pull-request-checks.yml
Labels: cla:yes

#1083 Fix permissions after bad conflict resolution
  .github/workflows/pull-request-checks.yml
Labels: cla:yes

#1035 Set partial ordering mode as default in dbt bigframes
  dbt-bigquery/.changes/unreleased/Fixes-20250429-230847.yaml
  dbt-bigquery/src/dbt/include/bigquery/macros/materializations/table.sql
Labels: cla:yes

#1070 Set 1 hour as default timeout in bigframes mode
  dbt-bigquery/.changes/unreleased/Fixes-20250507-164248.yaml
  dbt-bigquery/src/dbt/adapters/bigquery/python_submissions.py
  dbt-bigquery/tests/functional/adapter/test_python_model.py
Labels: cla:yes

#1025 Remove enable_iceberg_materializations behavior flag now that 2025_01 is required
  dbt-snowflake/.changes/unreleased/Under the Hood-20250425-185825.yaml
  dbt-snowflake/src/dbt/adapters/snowflake/impl.py
  dbt-snowflake/src/dbt/include/snowflake/macros/metadata/list_relations_without_caching.sql
  dbt-snowflake/src/dbt/include/snowflake/macros/relations/table/create.sql
  dbt-snowflake/tests/functional/adapter/list_relations_tests/test_show_objects.py
  dbt-snowflake/tests/functional/iceberg/test_incremental_models.py
  dbt-snowflake/tests/functional/iceberg/test_table_basic.py
  dbt-snowflake/tests/functional/relation_tests/dynamic_table_tests/test_basic.py
  dbt-snowflake/tests/functional/relation_tests/dynamic_table_tests/test_configuration_changes.py
  dbt-snowflake/tests/functional/relation_tests/test_relation_type_change.py
Labels: cla:yes, needs:docs

#1084 Fix workflow bugs
  .github/workflows/pull-request-checks.yml
Labels: cla:yes, skip:changelog-check

#1089 Use custom equality check instead of exact equality for access entries
  dbt-bigquery/tests/unit/test_dataset.py
Labels: cla:yes, skip:changelog-check

#1092 update error check to account for both types of logging
  dbt-redshift/tests/functional/adapter/test_exception_handling.py
Labels: cla:yes, skip:changelog-check

#1094 fix permissions
  .github/workflows/scheduled-tests.yml
Labels: cla:yes

#1068 Fix issue with check column snapshots in new_record mode.
  dbt-adapters/.changes/unreleased/Fixes-20250506-150345.yaml
  dbt-adapters/src/dbt/include/global_project/macros/materializations/snapshots/helpers.sql
  dbt-postgres/.changes/unreleased/Under the Hood-20250506-162028.yaml
  dbt-postgres/tests/functional/adapter/test_simple_snapshot.py
  dbt-redshift/.changes/unreleased/Under the Hood-20250506-162125.yaml
  dbt-redshift/tests/functional/adapter/test_simple_snapshot.py
  dbt-snowflake/.changes/unreleased/Under the Hood-20250506-162055.yaml
  dbt-snowflake/tests/functional/adapter/test_simple_snapshot.py
  dbt-tests-adapter/.changes/unreleased/Under the Hood-20250506-163044.yaml
  dbt-tests-adapter/src/dbt/tests/adapter/simple_snapshot/new_record_check_mode.py
  dbt-tests-adapter/src/dbt/tests/adapter/simple_snapshot/new_record_timestamp_mode.py
Labels: cla:yes

#1087 move protos into external dependency
  .pre-commit-config.yaml
  dbt-adapters/pyproject.toml
  dbt-adapters/src/dbt/adapters/events/README.md
  dbt-adapters/src/dbt/adapters/events/adapter_types.proto
  dbt-adapters/src/dbt/adapters/events/adapter_types_pb2.py
  dbt-adapters/src/dbt/adapters/events/base_types.py
  dbt-adapters/src/dbt/adapters/events/types.py
Labels: cla:yes, skip:changelog-check

#1098 We have some intermittent dependency chain resolution problems
  dbt-snowflake/.changes/unreleased/Under the Hood-20250514-160125.yaml
  dbt-snowflake/pyproject.toml
Labels: cla:yes

#1095 remove retry_all from add_query and set backoff>1
  dbt-redshift/.changes/unreleased/Fixes-20250513-104430.yaml
  dbt-redshift/src/dbt/adapters/redshift/connections.py
  dbt-redshift/tests/functional/adapter/test_exception_handling.py
  dbt-redshift/tests/unit/test_query.py
Labels: cla:yes

#1093 Set job_retry to None
  dbt-bigquery/.changes/unreleased/Fixes-20250513-105211.yaml
  dbt-bigquery/src/dbt/adapters/bigquery/connections.py
  dbt-bigquery/tests/unit/test_bigquery_connection_manager.py
Labels: cla:yes, ci:approve-public-fork-ci

#1097 fail when label is removed
  .github/workflows/pull-request-checks.yml
Labels: cla:yes

#1104 bump dbt-common pin to >=2.0,<3.0
  dbt-adapters/.changes/unreleased/Under the Hood-20250519-110215.yaml
  dbt-adapters/pyproject.toml
  dbt-athena/.changes/unreleased/Under the Hood-20250519-110215.yaml
  dbt-athena/pyproject.toml
  dbt-bigquery/.changes/unreleased/Under the Hood-20250519-110215.yaml
  dbt-bigquery/pyproject.toml
  dbt-postgres/.changes/unreleased/Under the Hood-20250519-110215.yaml
  dbt-postgres/pyproject.toml
  dbt-redshift/.changes/unreleased/Under the Hood-20250519-110215.yaml
  dbt-redshift/pyproject.toml
  dbt-snowflake/.changes/unreleased/Under the Hood-20250519-110215.yaml
  dbt-snowflake/pyproject.toml
  dbt-spark/.changes/unreleased/Under the Hood-20250519-110215.yaml
  dbt-spark/pyproject.toml
Labels: cla:yes

#1045 Added Support for api_endpoint config
  dbt-bigquery/.changes/unreleased/Features-20250501-081844.yaml
  dbt-bigquery/src/dbt/adapters/bigquery/clients.py
  dbt-bigquery/src/dbt/adapters/bigquery/credentials.py
  dbt-bigquery/tests/unit/test_bigquery_adapter.py
Labels: cla:yes, ci:approve-public-fork-ci

#1114 Mp/skip sample mode tests
  dbt-athena/tests/functional/adapter/test_sample_mode.py
  dbt-bigquery/tests/functional/adapter/test_python_model.py
  dbt-bigquery/tests/functional/adapter/test_sample_mode.py
  dbt-postgres/tests/functional/adapter/test_sample_mode.py
  dbt-redshift/tests/functional/adapter/test_sample_mode.py
  dbt-snowflake/tests/functional/adapter/test_python_model.py
  dbt-snowflake/tests/functional/adapter/test_sample_mode.py
Labels: cla:yes, skip:changelog-check

#1105 Add iceberg catalog support for dbt-bigquery
  .github/workflows/_integration-tests.yml
  dbt-bigquery/.changes/unreleased/Features-20250519-204651.yaml
  dbt-bigquery/src/dbt/adapters/bigquery/catalogs/__init__.py
  dbt-bigquery/src/dbt/adapters/bigquery/catalogs/_generic.py
  dbt-bigquery/src/dbt/adapters/bigquery/constants.py
  dbt-bigquery/src/dbt/adapters/bigquery/impl.py
  dbt-bigquery/src/dbt/adapters/bigquery/parse_model.py
  dbt-bigquery/src/dbt/include/bigquery/macros/adapters.sql
  dbt-bigquery/test.env.example
  dbt-bigquery/tests/functional/adapter/catalog_integration_tests/__init__.py
  dbt-bigquery/tests/functional/adapter/catalog_integration_tests/test_generic_catalog.py
  dbt-bigquery/tests/functional/adapter/relation_tests/__init__.py
  dbt-bigquery/tests/functional/adapter/relation_tests/models.py
  dbt-bigquery/tests/functional/adapter/relation_tests/test_relation_type_change.py
  dbt-bigquery/tests/functional/utils.py
Labels: cla:yes

#1115 Respect QUOTED_IDENTIFIERS_IGNORE_CASE with dynamic tables
  dbt-snowflake/.changes/unreleased/Fixes-20250522-031531.yaml
  dbt-snowflake/src/dbt/adapters/snowflake/impl.py
  dbt-snowflake/src/dbt/include/snowflake/macros/relations/dynamic_table/describe.sql
  dbt-snowflake/tests/functional/adapter/test_quoted_identifiers_flag.py
Labels: cla:yes

#1101 Fixed Casing Issue In Snapshot Target Validation
  dbt-adapters/.changes/unreleased/Fixes-20250515-165840.yaml
  dbt-adapters/src/dbt/adapters/base/impl.py
  dbt-tests-adapter/.changes/unreleased/Fixes-20250515-173320.yaml
  dbt-tests-adapter/src/dbt/tests/adapter/simple_snapshot/fixtures.py
Labels: cla:yes

#1131 Minor typo fix for test fixtures
  dbt-tests-adapter/src/dbt/tests/adapter/simple_snapshot/fixtures.py
Labels: cla:yes, skip:changelog-check, ci:approve-public-fork-ci
