Repository dbt-labs/dbt-adapters, pull requests merged in 2025-08, with the labels that each got.

#1192 Omit external volume from DDL when not provided
  dbt-snowflake/.changes/unreleased/Fixes-20250718-092225.yaml
  dbt-snowflake/src/dbt/adapters/snowflake/relation.py
Labels: cla:yes, ci:approve-public-fork-ci

#1177 Add BigQuery resource tags support via resource_tags config option
  dbt-bigquery/.changes/unreleased/Features-20250627-181243.yaml
  dbt-bigquery/src/dbt/adapters/bigquery/impl.py
  dbt-bigquery/src/dbt/adapters/bigquery/relation_configs/_options.py
  dbt-bigquery/tests/unit/test_bigquery_adapter.py
  dbt-bigquery/tests/unit/test_bigquery_options_config.py
  dbt-bigquery/tests/unit/test_bigquery_relation_configs.py
Labels: cla:yes, needs:docs, ci:approve-public-fork-ci

#1181 create table and column descriptions for snowflake iceberg tables
  dbt-snowflake/.changes/unreleased/Fixes-20250630-193240.yaml
  dbt-snowflake/src/dbt/include/snowflake/macros/adapters.sql
  dbt-snowflake/tests/unit/test_alter_relation_comment_macro.py
Labels: cla:yes, ci:approve-public-fork-ci

#1220 Fix a typo in a debug log
  dbt-athena/src/dbt/include/athena/macros/materializations/models/table/create_table_as.sql
Labels: cla:yes, skip:changelog-check

#1259 upgrade protobuf to 6.0
  dbt-adapters/.changes/unreleased/Dependencies-20250812-104909.yaml
  dbt-adapters/pyproject.toml
  dbt-snowflake/hatch.toml
Labels: cla:yes

#1257 override default varchar datatype when altering iceberg table columns
  dbt-snowflake/.changes/unreleased/Fixes-20250812-101959.yaml
  dbt-snowflake/src/dbt/include/snowflake/macros/adapters.sql
  dbt-snowflake/tests/functional/iceberg/test_iceberg_schema_change.py
Labels: cla:yes

#1275 Fix install script for spark session tests and pin dependency
  dbt-spark/dagger/requirements.txt
  dbt-spark/dagger/run_dbt_spark_tests.py
  dbt-spark/dagger/scripts/install_jdk.sh
  dbt-spark/hatch.toml
Labels: cla:yes

#1227 Improve promote workflow
  .github/workflows/promote.yml
Labels: cla:yes

#1253 Optimize extremely slow query that finds Postgres relations
  dbt-postgres/.changes/unreleased/Fixes-20250810-112403.yaml
  dbt-postgres/src/dbt/include/postgres/macros/relations.sql
Labels: cla:yes, ci:approve-public-fork-ci

#1283 move 1.10.1 release to `stable`
  dbt-bigquery/.changes/1.10.1.md
  dbt-bigquery/CHANGELOG.md
  dbt-bigquery/src/dbt/adapters/bigquery/__version__.py
Labels: cla:yes, skip:changelog-check

#1251 Add support for Iceberg REST Catalogs using a Catalog Linked Database
  .github/workflows/_integration-tests.yml
  dbt-adapters/src/dbt/adapters/catalogs/__init__.py
  dbt-adapters/src/dbt/adapters/catalogs/_exceptions.py
  dbt-adapters/src/dbt/adapters/exceptions/compilation.py
  dbt-snowflake/.changes/unreleased/Features-20250812-130838.yaml
  dbt-snowflake/hatch.toml
  dbt-snowflake/src/dbt/adapters/snowflake/catalogs/__init__.py
  dbt-snowflake/src/dbt/adapters/snowflake/catalogs/_iceberg_rest.py
  dbt-snowflake/src/dbt/adapters/snowflake/constants.py
  dbt-snowflake/src/dbt/adapters/snowflake/impl.py
  dbt-snowflake/src/dbt/adapters/snowflake/parse_model.py
  dbt-snowflake/src/dbt/include/snowflake/macros/get_custom_name.sql
  dbt-snowflake/src/dbt/include/snowflake/macros/relations/table/create.sql
  dbt-snowflake/test.env.example
  dbt-snowflake/tests/functional/adapter/catalog_integrations/test_iceberg_rest_catalog_integrations.py
  dbt-snowflake/tests/unit/test_iceberg_rest_catalog_integration.py
  dbt-snowflake/tests/unit/test_parse_model.py
Labels: cla:yes, skip:changelog-check

#1298 Fix wrong issue number
  dbt-bigquery/.changes/unreleased/Features-20250722-054150.yaml
Labels: cla:yes
