Repository dbt-labs/dbt-adapters, pull requests merged in 2025-04, with the labels that each got.

#962 Fix generate changelog linting
  .github/workflows/_generate-changelog.yml
  dbt-redshift/.changes/1.9.3.md
Labels: cla:yes, skip:changelog-check

#931 relax constraint on google-cloud-storage to allow newer versions
  dbt-bigquery/.changes/unreleased/Dependencies-20250321-205608.yaml
  dbt-bigquery/pyproject.toml
Labels: cla:yes, triage:support

#967 Update `list_relations_without_caching` macro to paginate using the same query
  dbt-snowflake/.changes/unreleased/Under the Hood-20250402-140022.yaml
  dbt-snowflake/src/dbt/adapters/snowflake/impl.py
  dbt-snowflake/src/dbt/include/snowflake/macros/adapters.sql
  dbt-snowflake/src/dbt/include/snowflake/macros/metadata/list_relations_without_caching.sql
Labels: cla:yes

#968 Create indexes on the intermediate relation before the swap
  dbt-adapters/.changes/unreleased/Fixes-20250402-130204.yaml
  dbt-adapters/src/dbt/include/global_project/macros/materializations/models/table.sql
Labels: cla:yes

#969 Create indexes on the target/intermediate/temp relation before the swap
  dbt-adapters/.changes/unreleased/Fixes-20250402-160530.yaml
  dbt-adapters/src/dbt/include/global_project/macros/materializations/models/incremental/incremental.sql
Labels: cla:yes

#950 Support default template creation and custom template
  dbt-bigquery/.changes/unreleased/Fixes-20250326-194701.yaml
  dbt-bigquery/src/dbt/adapters/bigquery/impl.py
  dbt-bigquery/src/dbt/adapters/bigquery/python_submissions.py
Labels: cla:yes

#970 fix the credential method issue
  dbt-bigquery/.changes/unreleased/Fixes-20250403-023401.yaml
  dbt-bigquery/src/dbt/adapters/bigquery/credentials.py
  dbt-bigquery/src/dbt/adapters/bigquery/python_submissions.py
Labels: cla:yes

#973 Add utility script for force cancelling workflows and allow cancellation of "always()" workflow jobs
  .github/workflows/_integration-tests.yml
  .github/workflows/publish-internal.yml
  .github/workflows/publish-oss.yml
  .github/workflows/pull-request-checks.yml
  .github/workflows/scheduled-tests.yml
  scripts/force-cancel-workflow.sh
Labels: cla:yes, skip:changelog-check

#956 fix typo thorews / throws
  dbt-tests-adapter/src/dbt/tests/adapter/aliases/test_aliases.py
Labels: cla:yes, skip:changelog-check, triage:quick_support_task

#949 support timeout in bigframes mode
  dbt-bigquery/.changes/unreleased/Features-20250326-184231.yaml
  dbt-bigquery/src/dbt/adapters/bigquery/python_submissions.py
Labels: cla:yes

#943 Format the outputs of notebook execution
  dbt-bigquery/.changes/unreleased/Fixes-20250326-002322.yaml
  dbt-bigquery/src/dbt/adapters/bigquery/python_submissions.py
Labels: cla:yes

#957 Use compute region to replace dataproc_region
  .github/workflows/_integration-tests.yml
  dbt-bigquery/.changes/unreleased/Fixes-20250401-002936.yaml
  dbt-bigquery/src/dbt/adapters/bigquery/clients.py
  dbt-bigquery/src/dbt/adapters/bigquery/credentials.py
  dbt-bigquery/src/dbt/adapters/bigquery/python_submissions.py
  dbt-bigquery/test.env.example
  dbt-bigquery/tests/conftest.py
  dbt-bigquery/tests/unit/test_bigquery_adapter.py
Labels: cla:yes

#981 Replace deprecated `datetime.utcnow()` with `datetime.now(timezone.utc).replace(tzinfo=None)`
  dbt-bigquery/.changes/unreleased/Fixes-20250408-104143.yaml
  dbt-bigquery/src/dbt/adapters/bigquery/token_suppliers.py
  dbt-postgres/.changes/unreleased/Fixes-20250408-104218.yaml
  dbt-postgres/src/dbt/adapters/postgres/impl.py
  dbt-postgres/tests/functional/sources/test_source_fresher_state.py
  dbt-postgres/tests/functional/sources/test_source_freshness.py
  dbt-redshift/.changes/unreleased/Fixes-20250408-104244.yaml
  dbt-redshift/tests/boundary/conftest.py
  dbt-snowflake/.changes/unreleased/Fixes-20250408-104306.yaml
  dbt-tests-adapter/.changes/unreleased/Fixes-20250408-104326.yaml
  dbt-tests-adapter/src/dbt/tests/adapter/basic/test_docs_generate.py
  dbt-tests-adapter/src/dbt/tests/adapter/utils/test_current_timestamp.py
Labels: cla:yes

#987 Run dbt-bigquery tests multithreaded
  dbt-bigquery/tests/conftest.py
Labels: cla:yes, skip:changelog-check

#996 Forward Unexpected Operations on Record/Replay Wrappers
  dbt-adapters/.changes/unreleased/Under the Hood-20250411-172257.yaml
  dbt-adapters/src/dbt/adapters/record/cursor/cursor.py
  dbt-adapters/src/dbt/adapters/record/handle.py
  dbt-adapters/tests/unit/record/__init__.py
  dbt-adapters/tests/unit/record/test_record_cursor.py
  dbt-adapters/tests/unit/record/test_record_handle.py
Labels: cla:yes

#995 chore: update proto namespaces to be more useful
  dbt-adapters/src/dbt/adapters/events/adapter_types.proto
Labels: cla:yes, skip:changelog-check

#932 ADAP-1170: Migrate managed catalog to the new catalog framework
  dbt-snowflake/.changes/unreleased/Features-20250321-182330.yaml
  dbt-snowflake/src/dbt/adapters/snowflake/catalogs/__init__.py
  dbt-snowflake/src/dbt/adapters/snowflake/catalogs/_iceberg_managed.py
  dbt-snowflake/src/dbt/adapters/snowflake/catalogs/_native.py
  dbt-snowflake/src/dbt/adapters/snowflake/constants.py
  dbt-snowflake/src/dbt/adapters/snowflake/impl.py
  dbt-snowflake/src/dbt/adapters/snowflake/parse_model.py
  dbt-snowflake/src/dbt/adapters/snowflake/relation.py
  dbt-snowflake/src/dbt/adapters/snowflake/relation_configs/__init__.py
  dbt-snowflake/src/dbt/adapters/snowflake/relation_configs/catalog.py
  dbt-snowflake/src/dbt/adapters/snowflake/relation_configs/dynamic_table.py
  dbt-snowflake/src/dbt/adapters/snowflake/relation_configs/formats.py
  dbt-snowflake/src/dbt/include/snowflake/macros/materializations/incremental.sql
  dbt-snowflake/src/dbt/include/snowflake/macros/materializations/table.sql
  dbt-snowflake/src/dbt/include/snowflake/macros/relations/dynamic_table/create.sql
  dbt-snowflake/src/dbt/include/snowflake/macros/relations/dynamic_table/describe.sql
  dbt-snowflake/src/dbt/include/snowflake/macros/relations/dynamic_table/replace.sql
  dbt-snowflake/src/dbt/include/snowflake/macros/relations/table/create.sql
  dbt-snowflake/src/dbt/include/snowflake/macros/utils/optional.sql
  dbt-snowflake/tests/functional/adapter/list_relations_tests/test_pagination.py
  dbt-snowflake/tests/functional/adapter/list_relations_tests/test_show_objects.py
  dbt-snowflake/tests/functional/iceberg/models.py
  dbt-snowflake/tests/functional/iceberg/test_incremental_models.py
  dbt-snowflake/tests/functional/iceberg/test_table_basic.py
  dbt-snowflake/tests/functional/relation_tests/test_relation_type_change.py
  dbt-snowflake/tests/unit/test_iceberg_location.py
  dbt-snowflake/tests/unit/test_parse_model.py
Labels: cla:yes, skip:changelog-check, pkg:dbt-snowflake

#989 Fix list_relation changes from #967
  dbt-snowflake/.changes/unreleased/Fixes-20250410-170947.yaml
  dbt-snowflake/src/dbt/include/snowflake/macros/metadata/list_relations_without_caching.sql
  dbt-snowflake/tests/functional/adapter/list_relations_tests/test_pagination.py
Labels: cla:yes

#1001 Make location optional in bigframes
  dbt-bigquery/.changes/unreleased/Fixes-20250416-170911.yaml
  dbt-bigquery/src/dbt/include/bigquery/macros/materializations/table.sql
Labels: cla:yes

#1003 Quick fix of the session in table.sql
  dbt-bigquery/.changes/unreleased/Fixes-20250416-211401.yaml
  dbt-bigquery/src/dbt/include/bigquery/macros/materializations/table.sql
Labels: cla:yes

#1007 Set job_timeout_ms in job config
  dbt-bigquery/.changes/unreleased/Fixes-20250418-163614.yaml
  dbt-bigquery/src/dbt/adapters/bigquery/connections.py
  dbt-bigquery/tests/functional/test_job_timeout.py
  dbt-bigquery/tests/unit/test_bigquery_connection_manager.py
Labels: cla:yes

#976 Raise an error when notebook execution failed
  dbt-bigquery/.changes/unreleased/Fixes-20250404-212327.yaml
  dbt-bigquery/src/dbt/adapters/bigquery/python_submissions.py
  dbt-bigquery/tests/functional/adapter/test_python_model.py
Labels: cla:yes

#978 Support custom package in bigframe mode
  dbt-bigquery/.changes/unreleased/Features-20250405-051305.yaml
  dbt-bigquery/src/dbt/adapters/bigquery/python_submissions.py
  dbt-bigquery/tests/functional/adapter/test_python_model.py
Labels: cla:yes

#947 dbt-athena: Rework iceberg full refresh for high availability
  dbt-athena/.changes/unreleased/Features-20250326-082108.yaml
  dbt-athena/src/dbt/include/athena/macros/materializations/models/incremental/incremental.sql
  dbt-athena/tests/functional/adapter/test_ha_iceberg.py
Labels: cla:yes, triage:ready-for-review

#1012 Add pointer relation type to the base adapter
  dbt-adapters/.changes/unreleased/Features-20250422-102717.yaml
  dbt-adapters/src/dbt/adapters/base/relation.py
  dbt-adapters/src/dbt/adapters/contracts/relation.py
  dbt-adapters/tests/unit/test_relation.py
Labels: cla:yes

#1011 Update info schema and built-in catalog references for dbt-snowflake
  dbt-snowflake/.changes/unreleased/Breaking Changes-20250422-101050.yaml
  dbt-snowflake/src/dbt/adapters/snowflake/catalogs/__init__.py
  dbt-snowflake/src/dbt/adapters/snowflake/catalogs/_built_in.py
  dbt-snowflake/src/dbt/adapters/snowflake/catalogs/_info_schema.py
  dbt-snowflake/src/dbt/adapters/snowflake/constants.py
  dbt-snowflake/src/dbt/adapters/snowflake/impl.py
  dbt-snowflake/src/dbt/adapters/snowflake/parse_model.py
  dbt-snowflake/src/dbt/adapters/snowflake/relation.py
  dbt-snowflake/src/dbt/include/snowflake/macros/relations/dynamic_table/create.sql
  dbt-snowflake/src/dbt/include/snowflake/macros/relations/dynamic_table/describe.sql
  dbt-snowflake/src/dbt/include/snowflake/macros/relations/dynamic_table/replace.sql
  dbt-snowflake/src/dbt/include/snowflake/macros/relations/table/create.sql
  dbt-snowflake/tests/unit/test_iceberg_location.py
Labels: cla:yes

#1019 Update namespace in proto bindings
  dbt-adapters/src/dbt/adapters/events/adapter_types_pb2.py
Labels: cla:yes, skip:changelog-check

#1027 Pin `certifi` to avoid issue with certificate authority update
  dbt-snowflake/.changes/unreleased/Fixes-20250426-231149.yaml
  dbt-snowflake/pyproject.toml
Labels: cla:yes

#1026 Support oauth secrets credential method in bigframes mode
  dbt-bigquery/.changes/unreleased/Features-20250425-230530.yaml
  dbt-bigquery/src/dbt/adapters/bigquery/credentials.py
  dbt-bigquery/src/dbt/adapters/bigquery/python_submissions.py
Labels: cla:yes

#1030 Make supported catalog lookup case-insensitive
  dbt-adapters/src/dbt/adapters/catalogs/_client.py
  dbt-adapters/src/dbt/adapters/catalogs/_exceptions.py
Labels: cla:yes, skip:changelog-check

#1014 retry_all + retry `could not open relation with OID` query exceptions
  dbt-adapters/src/dbt/adapters/sql/connections.py
  dbt-redshift/.changes/unreleased/Features-20250424-091102.yaml
  dbt-redshift/.changes/unreleased/Features-20250425-102549.yaml
  dbt-redshift/src/dbt/adapters/redshift/connections.py
  dbt-redshift/tests/functional/adapter/test_exception_handling.py
  dbt-redshift/tests/unit/test_query.py
Labels: cla:yes, skip:changelog-check

#1034 dbt-redshift: add serverless_work_group and serverless_acct_id params
  dbt-redshift/.changes/unreleased/Features-20250429-133335.yaml
  dbt-redshift/src/dbt/adapters/redshift/connections.py
  dbt-redshift/tests/unit/test_auth_method.py
Labels: cla:yes

#1033 Merge all flaky tests into the standard run
  .github/workflows/_integration-tests.yml
  dbt-redshift/hatch.toml
  dbt-redshift/tests/functional/adapter/catalog_tests/test_get_catalog.py
  dbt-redshift/tests/functional/adapter/catalog_tests/test_relation_types.py
  dbt-redshift/tests/functional/adapter/materialized_view_tests/test_materialized_views.py
  dbt-redshift/tests/functional/adapter/test_basic.py
  dbt-redshift/tests/functional/adapter/test_persist_docs.py
Labels: cla:yes, skip:changelog-check

#376 Respect the `limit` config when storing test failures
  dbt-adapters/.changes/unreleased/Fixes-20250426-190518.yaml
  dbt-adapters/src/dbt/include/global_project/macros/materializations/tests/helpers.sql
  dbt-adapters/src/dbt/include/global_project/macros/materializations/tests/test.sql
  dbt-postgres/tests/functional/adapter/test_store_test_failures.py
  dbt-tests-adapter/src/dbt/tests/adapter/store_test_failures_tests/fixtures.py
  dbt-tests-adapter/src/dbt/tests/adapter/store_test_failures_tests/test_store_test_failures.py
Labels: cla:yes, skip:changelog-check
