Repository dbt-labs/dbt-adapters, pull requests merged in 2025-01, with the labels that each got.

#385 Fix Snapshot Merge Query
  .changes/unreleased/Fixes-20241217-163126.yaml
  dbt-tests-adapter/dbt/tests/adapter/simple_snapshot/new_record_mode.py
  dbt/include/global_project/macros/materializations/snapshots/helpers.sql
Labels: cla:yes

#186 Update replace.sql
  .changes/unreleased/Fixes-20240425-133610.yaml
  dbt/include/global_project/macros/relations/replace.sql
Labels: cla:yes, community

#400 bump dbt-adapters to 1.13.1 and dbt-tests-adapters to 1.10.5
  dbt-tests-adapter/dbt/tests/__about__.py
  dbt/adapters/__about__.py
Labels: cla:yes

#517 ADAP-1166: Add table format telemetry reporting to Spark adapter
  dbt-spark/src/dbt/adapters/spark/impl.py
  dbt-spark/tests/unit/test_adapter_telemetry.py
Labels: cla:yes

#612 bump `dbt-adapters` to `1.13.2`
  dbt/adapters/__about__.py
Labels: cla:yes

#613 Update publish.yml
  .github/workflows/publish.yml
Labels: cla:yes

#614 Update publish.yml
  .github/workflows/_publish-internal.yml
  .github/workflows/publish.yml
Labels: cla:yes

#747 Unblock PRs getting hung up by this test.
  dbt-redshift/tests/functional/test_auth_method.py
Labels: cla:yes

#751 Update _publish-internal.yml
  .github/workflows/_publish-internal.yml
Labels: cla:yes

#755 Run flaky tests in their own job so that they can be rerun independently
  .github/workflows/_integration-tests.yml
  dbt-redshift/pyproject.toml
Labels: cla:yes, Skip Changelog

#606 ADAP-1126: Filter pull request checks to only impacted packages
  .github/filters/changelog-entry-check.yml
  .github/filters/integration-tests.yml
  .github/filters/unit-tests.yml
  .github/filters/verify-build.yml
  .github/workflows/pull-request-checks.yml
Labels: cla:yes

#759 Fix the filters workflow
  .github/workflows/pull-request-checks.yml
Labels: cla:yes

#403 ADAP-1167: Add table format telemetry reporting to Athena adapter
  dbt-athena/src/dbt/adapters/athena/impl.py
  dbt-athena/tests/functional/adapter/test_retries_iceberg.py
  dbt-athena/tests/unit/test_adapter_telemetry.py
Labels: cla:yes

#607 ADAP-1178: Add scheduled testing workflow
  .github/workflows/_integration-tests.yml
  .github/workflows/pull-request-checks.yml
  .github/workflows/scheduled-tests.yml
Labels: cla:yes

#762 Update the environment dropdown to a hard coded list
  .github/workflows/publish.yml
Labels: cla:yes
