Repository dbt-labs/dbt-adapters, pull requests merged in 2025-07, with the labels that each got.

#1176 dbt snowflake/quote columns when altering
  dbt-snowflake/.changes/unreleased/Fixes-20250626-161248.yaml
  dbt-snowflake/src/dbt/include/snowflake/macros/adapters.sql
  dbt-snowflake/tests/functional/adapter/incremental/test_incremental_on_schema_change.py
Labels: cla:yes

#1174 Fix Snapshot behavior in new_record mode for records already marked as deleted (reopened)
  dbt-adapters/.changes/unreleased/Fixes-20250626-112659.yaml
  dbt-adapters/src/dbt/include/global_project/macros/materializations/snapshots/helpers.sql
  dbt-tests-adapter/.changes/unreleased/Under the Hood-20250627-092211.yaml
  dbt-tests-adapter/src/dbt/tests/adapter/simple_snapshot/new_record_timestamp_mode.py
Labels: cla:yes, ci:approve-public-fork-ci

#1194 add support for `tcp_keepalive`
  dbt-redshift/.changes/unreleased/Features-20250710-110711.yaml
  dbt-redshift/pyproject.toml
  dbt-redshift/src/dbt/adapters/redshift/connections.py
  dbt-redshift/tests/functional/conftest.py
  dbt-redshift/tests/unit/test_auth_method.py
  dbt-redshift/tests/unit/test_connection.py
  dbt-redshift/tests/unit/test_ssl_mode.py
Labels: cla:yes, feature:docs

#1198 skip clone if target and defer relation are the same
  dbt-adapters/.changes/unreleased/Fixes-20250714-103018.yaml
  dbt-adapters/src/dbt/include/global_project/macros/materializations/models/clone/clone.sql
  dbt-bigquery/tests/functional/adapter/dbt_clone/test_dbt_clone.py
  dbt-snowflake/tests/functional/adapter/dbt_clone/test_dbt_clone.py
  dbt-tests-adapter/.changes/unreleased/Features-20250714-104451.yaml
  dbt-tests-adapter/src/dbt/tests/adapter/dbt_clone/fixtures.py
  dbt-tests-adapter/src/dbt/tests/adapter/dbt_clone/test_dbt_clone.py
Labels: cla:yes

#1199 add write catalog doc
  docs/guides/write_catalog.md
Labels: cla:yes

#1201 Support new column in source table with hard_deletes = new_record
  dbt-adapters/.changes/unreleased/Fixes-20250715-125933.yaml
  dbt-adapters/src/dbt/include/global_project/macros/adapters/columns.sql
  dbt-adapters/src/dbt/include/global_project/macros/materializations/snapshots/helpers.sql
  dbt-snowflake/tests/functional/adapter/test_ephemeral_snapshot_hard_deletes.py
  dbt-tests-adapter/.changes/unreleased/Features-20250715-131036.yaml
  dbt-tests-adapter/src/dbt/tests/adapter/simple_snapshot/test_ephemeral_snapshot_hard_deletes.py
Labels: cla:yes

#1203 Alter/Rename Dynamic Tables on full refresh
  dbt-snowflake/.changes/unreleased/Fixes-20250716-095518.yaml
  dbt-snowflake/src/dbt/adapters/snowflake/relation.py
  dbt-snowflake/src/dbt/include/snowflake/macros/relations/dynamic_table/rename.sql
  dbt-snowflake/tests/functional/relation_tests/dynamic_table_tests/models.py
  dbt-snowflake/tests/functional/relation_tests/dynamic_table_tests/test_full_refresh_custom_schema.py
  dbt-snowflake/tests/unit/test_renamed_relations.py
Labels: cla:yes

#1204 update alter_relation_add_remove_columns to quote column names
  dbt-adapters/.changes/unreleased/Fixes-20250716-154809.yaml
  dbt-adapters/src/dbt/include/global_project/macros/adapters/columns.sql
  dbt-athena/src/dbt/adapters/athena/column.py
  dbt-athena/src/dbt/include/athena/macros/materializations/models/incremental/column_helpers.sql
  dbt-athena/tests/functional/adapter/test_on_schema_change.py
  dbt-bigquery/tests/functional/adapter/incremental/test_incremental_on_schema_change.py
  dbt-postgres/tests/functional/adapter/test_incremental.py
  dbt-redshift/.changes/unreleased/Fixes-20250716-154809.yaml
  dbt-redshift/src/dbt/include/redshift/macros/adapters.sql
  dbt-redshift/tests/functional/adapter/incremental/test_incremental_on_schema_change.py
  dbt-spark/.changes/unreleased/Fixes-20250716-154809.yaml
  dbt-spark/src/dbt/include/spark/macros/adapters.sql
  dbt-spark/tests/functional/adapter/incremental/test_incremental_on_schema_change.py
  dbt-tests-adapter/src/dbt/tests/adapter/incremental/fixtures.py
Labels: cla:yes, skip:changelog-check

#1216 Gracefully handle None database or schemas
  dbt-adapters/.changes/unreleased/Under the Hood-20250721-120840.yaml
  dbt-adapters/src/dbt/adapters/base/impl.py
  dbt-postgres/tests/unit/test_filter_catalog.py
Labels: cla:yes

#1218 add promote workflow
  .github/workflows/promote.yml
Labels: cla:yes, skip:changelog-check
