Repository dbt-labs/dbt-adapters, pull requests merged in 2025-02, with the labels that each got.

#765 Quickfix: force publish action to use aws profile
  .github/workflows/_publish-internal.yml
Labels: cla:yes

#777 Fix issue templates and triage
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/regression-report.yml
  .github/workflows/_changelog-entry-check.yml
  .github/workflows/issue-triage.yml
  .github/workflows/scheduled-maintenance.yml
  .github/workflows/user-docs.yml
Labels: cla:yes, skip:changelog-check

#778 Update project URLs for all adapters
  dbt-adapters/pyproject.toml
  dbt-athena-community/pyproject.toml
  dbt-athena/pyproject.toml
  dbt-bigquery/pyproject.toml
  dbt-postgres/pyproject.toml
  dbt-redshift/pyproject.toml
  dbt-snowflake/pyproject.toml
  dbt-spark/pyproject.toml
  dbt-tests-adapter/pyproject.toml
Labels: cla:yes, skip:changelog-check

#779 Add license to each package and standardize on file name
  dbt-athena-community/LICENSE
  dbt-athena/LICENSE
  dbt-bigquery/LICENSE
  dbt-postgres/LICENSE
  dbt-redshift/LICENSE
  dbt-snowflake/LICENSE
  dbt-spark/LICENSE
  dbt-tests-adapter/LICENSE
Labels: cla:yes, skip:changelog-check

#787 ADAP-1208: Fix publish workflow for `dbt-tests-adapter`
  .github/workflows/publish.yml
Labels: cla:yes

#797 Fix snowflake testing
  dbt-snowflake/hatch.toml
  dbt-snowflake/tests/functional/iceberg/models.py
Labels: cla:yes

#801 Fix publish workflow conditions
  .github/workflows/publish.yml
Labels: cla:yes, skip:changelog-check

#758 Implement drop_glue_database macro and method
  dbt-adapters/.changes/1.14.0.md
  dbt-adapters/CHANGELOG.md
  dbt-adapters/src/dbt/adapters/sql/connections.py
  dbt-athena/.changes/1.9.1.md
  dbt-athena/.changes/unreleased/Features-20250129-121455.yaml
  dbt-athena/CHANGELOG.md
  dbt-athena/src/dbt/adapters/athena/impl.py
  dbt-athena/src/dbt/include/athena/macros/adapters/schema.sql
  dbt-athena/tests/unit/test_adapter.py
  dbt-tests-adapter/.changes/1.11.0.md
  dbt-tests-adapter/CHANGELOG.md
Labels: cla:yes

#816 skip TestDocsGenerateBigQuery
  dbt-bigquery/tests/functional/adapter/test_basic.py
Labels: cla:yes

#813 update .gitignore to exclude test.env and code-workspace files
  .gitignore
Labels: cla:yes

#798 replace DbtRuntime exception with DbtDatabase exception in dbt-bigquery
  dbt-bigquery/.changes/unreleased/Under the Hood-20250206-103950.yaml
  dbt-bigquery/src/dbt/adapters/bigquery/connections.py
Labels: cla:yes

#780 Standardize pytest config and env files
  .github/filters/changelog-entry-check.yml
  .github/filters/integration-tests.yml
  .github/filters/unit-tests.yml
  .github/filters/verify-build.yml
  .github/workflows/_integration-tests.yml
  .github/workflows/publish.yml
  .github/workflows/pull-request-checks.yml
  .github/workflows/scheduled-tests.yml
  dbt-adapters/pyproject.toml
  dbt-athena-community/pyproject.toml
  dbt-athena/pyproject.toml
  dbt-athena/test.env.example
  dbt-bigquery/pyproject.toml
  dbt-postgres/pyproject.toml
  dbt-postgres/test.env.example
  dbt-redshift/pyproject.toml
  dbt-snowflake/pyproject.toml
  dbt-spark/pyproject.toml
Labels: cla:yes, skip:changelog-check

#817 Fix pull request integration tests
  .github/filters/integration-tests.yml
  .github/workflows/pull-request-checks.yml
  dbt-athena-community/pyproject.toml
Labels: cla:yes

#820 Fix the changelog check
  .github/workflows/_changelog-entry-check.yml
Labels: cla:yes

#822 Update changelogs with links to prior versions
  dbt-bigquery/.changes/0.0.0.md
  dbt-bigquery/CHANGELOG.md
  dbt-redshift/.changes/0.0.0.md
  dbt-redshift/CHANGELOG.md
  dbt-snowflake/.changes/0.0.0.md
  dbt-snowflake/CHANGELOG.md
  dbt-spark/.changes/0.0.0.md
  dbt-spark/CHANGELOG.md
Labels: cla:yes

#819 add is serverless param
  dbt-redshift/.changes/unreleased/Features-20250213-121903.yaml
  dbt-redshift/src/dbt/adapters/redshift/connections.py
  dbt-redshift/tests/unit/test_auth_method.py
  dbt-redshift/tests/unit/test_ssl_mode.py
Labels: cla:yes, type:documentation

#821 handle null result from backend_pid check
  dbt-redshift/.changes/unreleased/Under the Hood-20250214-110107.yaml
  dbt-redshift/src/dbt/adapters/redshift/connections.py
Labels: cla:yes

#462 ADAP-1184: Create scripts to streamline moving branches into the monorepo and backporting bug fixes to legacy repos
  CONTRIBUTING.md
  scripts/backport-to-legacy-repo.sh
  scripts/migrate-adapter.sh
  scripts/migrate-branch.sh
Labels: cla:yes

#828 ADAP-1231: Automate internal releases
  .github/workflows/_publish-internal.yml
  .github/workflows/publish-internal.yml
  .github/workflows/publish-oss.yml
  .github/workflows/publish-scheduled.yml
Labels: cla:yes

#835 Remove inadvertent pin to align with the prior version of dbt-snowflake
  dbt-snowflake/.changes/unreleased/Fixes-20250221-093358.yaml
  dbt-snowflake/pyproject.toml
Labels: cla:yes

#836 ADAP-1234: Allow for tests to be skipped for internal publishing
  .github/workflows/publish-internal.yml
Labels: cla:yes

#831 ADAP-1232: Fix unit test issues
  .github/workflows/_unit-tests.yml
  dbt-athena/tests/unit/test_adapter.py
  dbt-snowflake/tests/unit/test_private_keys.py
Labels: cla:yes

#832 ADAP-1233: Fix the databricks startup fixture
  dbt-spark/tests/functional/__init__.py
  dbt-spark/tests/functional/conftest.py
  dbt-spark/tests/functional/fixtures/__init__.py
  dbt-spark/tests/functional/fixtures/profiles.py
  dbt-spark/tests/functional/fixtures/start_databricks_cluster.py
Labels: cla:yes

#844 ADAP-1233: Wait for databricks to start up
  dbt-spark/tests/functional/fixtures/start_databricks_cluster.py
Labels: cla:yes, skip:changelog-check

#838 ADAP-1235: Fix test_persist_docs missing column test
  dbt-spark/tests/functional/adapter/persist_docs/test_persist_docs.py
Labels: cla:yes, skip:changelog-check

#834 Improve performance of `delete+insert` incremental strategy with null equality check changes
  dbt-adapters/.changes/unreleased/Fixes-20250221-092716.yaml
  dbt-adapters/src/dbt/include/global_project/macros/materializations/models/incremental/merge.sql
Labels: cla:yes

#856 port over PR.
  dbt-spark/.changes/unreleased/Fixes-20250228-073629.yaml
  dbt-spark/src/dbt/adapters/spark/relation.py
  dbt-spark/tests/functional/adapter/empty/test_empty.py
Labels: cla:yes
