Repository dbt-labs/dbt-adapters, pull requests merged in 2025-06, with the labels that each got.

#1129 bigquery storage_uri updates
  dbt-bigquery/.changes/unreleased/Features-20250529-092932.yaml
  dbt-bigquery/.changes/unreleased/Under the Hood-20250603-114705.yaml
  dbt-bigquery/.changes/unreleased/Under the Hood-20250603-114746.yaml
  dbt-bigquery/src/dbt/adapters/bigquery/catalogs/__init__.py
  dbt-bigquery/src/dbt/adapters/bigquery/catalogs/_biglake_metastore.py
  dbt-bigquery/src/dbt/adapters/bigquery/catalogs/_generic.py
  dbt-bigquery/src/dbt/adapters/bigquery/catalogs/_info_schema.py
  dbt-bigquery/src/dbt/adapters/bigquery/catalogs/_relation.py
  dbt-bigquery/src/dbt/adapters/bigquery/constants.py
  dbt-bigquery/src/dbt/adapters/bigquery/impl.py
  dbt-bigquery/src/dbt/adapters/bigquery/parse_model.py
  dbt-bigquery/tests/functional/adapter/catalog_integrations/test_catalog_integration.py
  dbt-bigquery/tests/unit/test_catalog_integrations.py
Labels: cla:yes, skip:changelog-check

#1142 bump dbt-core requirement to 1.10.0rc0
  dbt-bigquery/.changes/unreleased/Dependencies-20250604-110253.yaml
  dbt-bigquery/pyproject.toml
Labels: cla:yes

#1121 Adap 1032/fix redshift incremental merge ddl
  dbt-redshift/.changes/unreleased/Fixes-20250605-145421.yaml
  dbt-redshift/src/dbt/include/redshift/macros/materializations/incremental_delete_insert.sql
  dbt-redshift/tests/functional/adapter/incremental/test_delete_insert_merge.py
Labels: cla:yes

#1148 bq sf/set lower bound on base adapter
  dbt-bigquery/.changes/unreleased/Dependencies-20250609-135552.yaml
  dbt-bigquery/pyproject.toml
  dbt-snowflake/.changes/unreleased/Dependencies-20250609-135623.yaml
  dbt-snowflake/pyproject.toml
Labels: cla:yes

#1152 Add user agent in bigframes mode
  dbt-bigquery/.changes/unreleased/Features-20250612-000557.yaml
  dbt-bigquery/src/dbt/include/bigquery/macros/materializations/table.sql
Labels: cla:yes, ci:approve-public-fork-ci

#977 Add create_notebook_client in clients.py
  dbt-bigquery/.changes/unreleased/Fixes-20250404-215640.yaml
  dbt-bigquery/src/dbt/adapters/bigquery/clients.py
  dbt-bigquery/src/dbt/adapters/bigquery/python_submissions.py
Labels: cla:yes, ci:approve-public-fork-ci

#1159 stop setting quoted_identifiers_ignore_case
  dbt-snowflake/.changes/unreleased/Under the Hood-20250616-155209.yaml
  dbt-snowflake/src/dbt/adapters/snowflake/impl.py
  dbt-snowflake/src/dbt/include/snowflake/macros/metadata/list_relations_without_caching.sql
  dbt-snowflake/tests/functional/adapter/test_quoted_identifiers_flag.py
Labels: cla:yes

#1158 add support for optional iceberg builtin catalog relation parameters
  dbt-snowflake/.changes/unreleased/Features-20250616-111008.yaml
  dbt-snowflake/src/dbt/adapters/snowflake/catalogs/__init__.py
  dbt-snowflake/src/dbt/adapters/snowflake/catalogs/_built_in.py
  dbt-snowflake/src/dbt/adapters/snowflake/constants.py
  dbt-snowflake/src/dbt/adapters/snowflake/parse_model.py
  dbt-snowflake/src/dbt/include/snowflake/macros/relations/table/create.sql
  dbt-snowflake/tests/functional/adapter/catalog_integrations/test_catalog_integrations.py
  dbt-snowflake/tests/unit/test_catalog_relation_built_in.py
Labels: cla:yes

#1162 Add s3_stage_vpce_dns_name session param
  dbt-snowflake/.changes/unreleased/Features-20250618-084607.yaml
  dbt-snowflake/src/dbt/adapters/snowflake/connections.py
  dbt-snowflake/tests/functional/s3_stage_vpce_dns_name/test_s3_stage_vpce_dns_name.py
Labels: cla:yes

#1173 Update _integration-tests.yml
  .github/workflows/_integration-tests.yml
Labels: cla:yes

#1169 dbt snowflake/fix get relations with quoted identifiers
  dbt-snowflake/.changes/unreleased/Fixes-20250623-110029.yaml
  dbt-snowflake/src/dbt/adapters/snowflake/impl.py
  dbt-snowflake/tests/unit/test_snowflake_adapter.py
Labels: cla:yes
